"""add_shipping_date_to_shipments

Revision ID: 3430adc0c2a6
Revises: 002
Create Date: 2026-04-27 13:36:12.890505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3430adc0c2a6'
down_revision: Union[str, None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_shipment_tracking_events_shipment_id'), 'shipment_tracking_events', ['shipment_id'], unique=False)
    op.add_column('shipments', sa.Column('shipping_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'shipping_date')
    op.drop_index(op.f('ix_shipment_tracking_events_shipment_id'), table_name='shipment_tracking_events')
    # ### end Alembic commands ###
